### ISSUE TITLE
Freezing top row of table 

### ISSUE THREAD

**Issue by EcZX** [RockefellerArchiveCenter/aurora#340]
## Is your feature request related to a problem? Please describe.
When you scroll down with too many results, the top row goes away (under the transfer, appraise and accession pages) which result in scrolling back and forth a lot.

## Describe the solution you'd like
Is there a way to freeze the top row or make it so that it moves in sync when scrolling. 

## Additional context
Feel free to disagree but I feel it kills a lot of time scrolling back and forth.

**Comment by helrond** [comment]
@EcZX I'd like to propose a different approach to this (and #339) which is simply to reduce the number of items on each page of the table, ideally making it so that users can choose how many items they want on a page. This will be a far less invasive changes. I'm not convinced that all users will share your aversion to scrolling but it's also good practice to give users the ability to decide how they want the application to look. What do you think?

https://datatables.net/reference/option/lengthMenu

**Comment by EcZX** [comment]
@helrond I think you make a great point! As for #339, I will talk to some of the folks that requested this change and see what they think about this alternative.

**Comment by helrond** [comment]
I would also be interested in hearing a bit more about the context in which this scrolling causes users to look track of what they're looking at. There may be some other ways of solving this issue that we haven't considered yet.
